import json
import os

# Directory containing the language files
lang_dir = "../p3/libs/lang/"

# Translations dictionary: key -> {lang_code: translation}
translations = {
    "needed_requirements_title": {
        "am": "መስፈርቶች",
        "ar": "المتطلبات",
        "az": "Tələblər",
        "bg": "Изисквания",
        "bn": "প্রয়োজনীয়তা",
        "bs": "Zahtjevi",
        "cs": "Požadavky",
        "da": "Krav",
        "de": "Anforderungen",
        "el": "Απαιτήσεις",
        "es": "Requisitos",
        "et": "Nõuded",
        "fa": "الدرجات المطلوبة",
        "fi": "Vaatimukset",
        "fr": "Prérequis",
        "ga": "Riachtanais",
        "he": "דרישות",
        "hi": "आवश्यकताएं",
        "hr": "Zahtjevi",
        "hu": "Követelmények",
        "hy": "Պահանջներ",
        "id": "Persyaratan",
        "is": "Kröfur",
        "it": "Requisiti",
        "ja": "要件",
        "ka": "მოთხოვნები",
        "km": "តម្រូវការ",
        "ko": "요구 사항",
        "lo": "ຄວາມຕ້ອງການ",
        "lt": "Reikalavimai",
        "lv": "Prasības",
        "mn": "Шаардлага",
        "ms": "Keperluan",
        "my": "လိုအပ်ချက်များ",
        "nb": "Krav",
        "ne": "आवश्यकताहरू",
        "nl": "Vereisten",
        "pl": "Wymagania",
        "pt": "Requisitos",
        "ro": "Cerințe",
        "ru": "Требования",
        "sk": "Požiadavky",
        "sl": "Zahteve",
        "sq": "Kërkesa",
        "sr": "Захтеви",
        "sv": "Krav",
        "sw": "Mahitaji",
        "ta": "தேவைகள்",
        "tg": "Талаботҳо",
        "th": "ข้อกำหนด",
        "tl": "Mga Kinakailangan",
        "tr": "Gereksinimler",
        "uk": "Вимоги",
        "ur": "ضروریات",
        "uz": "Talablar",
        "vi": "Yêu cầu",
        "zh": "要求",
    },
    "needed_requirements_message": {
        "am": "ከ{script_name} ጋር ወደ ፊት ከመስፈር በፊት የሚከተሉት ባህሪዎች ያስፈልጋሉ:",
        "ar": "المميزات التالية مطلوبة قبل المتابعة مع {script_name}:",
        "az": "{script_name} ilə davam etməzdən əvvəl aşağıdakı xüsusiyyətlər tələb olunur:",
        "bg": "Следните функции са необходими преди да продължите с {script_name}:",
        "bn": "{script_name} এর সাথে এগিয়ে যাওয়ার আগে নিম্নলিখিত বৈশিষ্ট্যগুলি প্রয়োজন:",
        "bs": "Sljedeće osobine su obavezne prije nastavka s {script_name}:",
        "cs": "Následující funkce jsou vyžadovány před pokračováním v {script_name}:",
        "da": "Følgende funktioner er påkrevede før fortsættelsen af {script_name}:",
        "de": "Die folgenden Funktionen sind erforderlich, bevor Sie {script_name} fortsetzen:",
        "el": "Τα ακόλουθα χαρακτηριστικά απαιτούνται πριν προχωρήσετε με {script_name}:",
        "es": "Las siguientes funciones son necesarias antes de continuar con {script_name}:",
        "et": "Järgmised funktsioonid on nõutavad enne {script_name} jätkamist:",
        "fa": "ویژگی های زیر قبل از ادامه با {script_name} مورد نیاز است:",
        "fi": "Seuraavat ominaisuudet vaaditaan ennen kuin jatkat {script_name}:",
        "fr": "Les fonctionnalités suivantes sont requises avant de continuer avec {script_name}:",
        "ga": "Tá gá do na gné agus a leanas roimh bhraistint ar aghaidh le {script_name}:",
        "he": "התכונות הבאות נדרשות לפני שתמשיכו עם {script_name}:",
        "hi": "{script_name} के साथ आगे बढ़ने से पहले निम्नलिखित विशेषताएं आवश्यक हैं:",
        "hr": "Sljedeće osobine su potrebne prije nego što nastavite s {script_name}:",
        "hu": "A következő funkciók szükségesek, mielőtt folytatna a {script_name} verzióval:",
        "hy": "Հետևյալ գործառույթները անհրաժեշտ են {script_name}-ի հետ շարունակելուց առաջ:",
        "id": "Fitur-fitur berikut diperlukan sebelum melanjutkan dengan {script_name}:",
        "is": "Eftirfarandi eiginleikar eru nauðsynlegir áður en haldið er áfram með {script_name}:",
        "it": "Le seguenti funzioni sono necessarie prima di continuare con {script_name}:",
        "ja": "{script_name} を続行する前に、次の機能が必要です:",
        "ka": "შემდეგი ფუნქციები აუცილებელია {script_name}-ით გაგრძელებამდე:",
        "km": "មុខងារខាងក្រោមគឺត្រូវការ មុនពេលលេងបន្តទៅ {script_name}:",
        "ko": "{script_name}을(를) 계속하기 전에 다음 기능이 필요합니다:",
        "lo": "ຄຸນສົມບັດດັ່ງຕໍ່ໄປນີ້ແມ່ນຈໍາເປັນກ່ອນທີ່ຈະດໍາເນີນການກັບ {script_name}:",
        "lt": "Toliau nurodytai funkcijos reikalingos prieš tęsiant {script_name}:",
        "lv": "Šādas funkcijas ir nepieciešamas pirms turpināšanas ar {script_name}:",
        "mn": "Дараа дх бүтээлүүд {script_name}-тай үргэлжлүүлэхээс өмнө шаардлагатай:",
        "ms": "Ciri-ciri berikut diperlukan sebelum melanjutkan dengan {script_name}:",
        "my": "{script_name} ကို ဆက်လက်လုပ်ဆောင်မီ အောက်ပါ အင်္ဂါရပ်များ လိုအပ်ပါသည်:",
        "nb": "Følgende funksjoner kreves før du fortsetter med {script_name}:",
        "ne": "{script_name} सँग अगाडि बढ्नु अघि निम्नलिखित सुविधाहरू आवश्यक छन्:",
        "nl": "De volgende functies zijn vereist voordat u doorgaat met {script_name}:",
        "pl": "Poniższe funkcje są wymagane przed kontynuacją {script_name}:",
        "pt": "Os seguintes recursos são necessários antes de prosseguir com {script_name}:",
        "ro": "Următoarele funcții sunt necesare înainte de a continua cu {script_name}:",
        "ru": "Перед продолжением работы с {script_name} требуются следующие функции:",
        "sk": "Nasledujúce funkcie sú potrebné pred pokračovaním s {script_name}:",
        "sl": "Naslednje funkcije so potrebne pred nadaljevanjem s {script_name}:",
        "sq": "Veçoritë e mëposhtme janë të nevojshme para se të vazhdohet me {script_name}:",
        "sr": "Следеће функције су потребне пре него што наставите са {script_name}:",
        "sv": "Följande funktioner krävs innan du fortsätter med {script_name}:",
        "sw": "Sifa zifuatazo zinahitajika kabla ya kuendelea na {script_name}:",
        "ta": "{script_name} உடன் தொடர்வதற்கு முன் பின்வரும் அம்சங்கள் தேவை:",
        "tg": "Хусусиятҳои зеринро пеш аз идома бо {script_name} талаб мекунанд:",
        "th": "จำเป็นต้องมีฟีเจอร์ต่อไปนี้ก่อนที่จะดำเนินการต่อด้วย {script_name}:",
        "tl": "Ang mga sumusunod na feature ay kinakailangan bago magpatuloy sa {script_name}:",
        "tr": "{script_name} ile devam etmeden önce aşağıdaki özellikler gereklidir:",
        "uk": "Перед продовженням роботи з {script_name} необхідні такі функції:",
        "ur": "{script_name} کے ساتھ آگے بڑھنے سے پہلے درج ذیل خصوصیات ضروری ہیں:",
        "uz": "{script_name} bilan davom etishdan oldin quyidagi xususiyatlar talab qilinadi:",
        "vi": "Các tính năng sau đây cần thiết trước khi tiếp tục với {script_name}:",
        "zh": "继续使用 {script_name} 之前需要以下功能:",
    },
    "needed_requirements_footer": {
        "am": "እነዚህ አስፈላጊ ባህሪዎች መጀመሪያ ይገጠሙታል፣ ከዚያ ዋናው ስክሪፕት ይቀጥላል።",
        "ar": "سيتم تثبيت هذه الميزات المطلوبة أولاً، ثم سيستمر البرنامج الرئيسي.",
        "az": "Bu tələb olunan xüsusiyyətlər əvvəlcə quraşdırılacaq, sonra əsas skript davam edəcəkdir.",
        "bg": "Тези необходими функции ще бъдат инсталирани първо, след което основният скрипт ще продължи.",
        "bn": "এই প্রয়োজনীয় বৈশিষ্ট্যগুলি প্রথমে ইনস্টল করা হবে, তারপর প্রধান স্ক্রিপ্ট চলতে থাকবে।",
        "bs": "Ove obavezne osobine će biti instalirane prvo, a zatim će glavni skript nastaviti.",
        "cs": "Tyto požadované funkce budou nainstalovány jako první, poté bude pokračovat hlavní skript.",
        "da": "Disse påkrevede funktioner vil blive installeret først, derefter vil hovedscriptet fortsætte.",
        "de": "Diese erforderlichen Funktionen werden zuerst installiert, dann wird das Hauptskript fortgesetzt.",
        "el": "Αυτές οι απαιτούμενες λειτουργίες θα εγκατασταθούν πρώτα, στη συνέχεια το κύριο σενάριο θα συνεχιστεί.",
        "es": "Estas funciones necesarias se instalarán primero, luego continuará el script principal.",
        "et": "Need nõutavad funktsioonid paigaldatakse esmalt, seejärel jätkub peamine skript.",
        "fa": "این ویژگی های مورد نیاز ابتدا نصب خواهند شد، سپس اسکریپت اصلی ادامه خواهد یافت.",
        "fi": "Nämä vaaditut ominaisuudet asennetaan ensin, minkä jälkeen pääskripti jatkuu.",
        "fr": "Ces fonctionnalités requises seront installées en premier, puis le script principal continuera.",
        "ga": "Suiteofar na gné riachtanacha seo ar dtús, ansin leanfaidh an príomhscript ar aghaidh.",
        "he": "תכונות נדרשות אלה יותקנו תחילה, ואז הסקריפט הראשי יימשך.",
        "hi": "ये आवश्यक विशेषताएं पहले स्थापित की जाएंगी, फिर मुख्य स्क्रिप्ट जारी रहेगी।",
        "hr": "Ove obavezne osobine će biti instalirane prvo, a zatim će se glavni skript nastaviti.",
        "hu": "Ezek a szükséges funkciók először telepítésre kerülnek, majd a fő szkript folytatódik.",
        "hy": "Այս անհրաժեշտ գործառույթները կտեղադրվեն առաջին հերթին, ապա հիմնական սկրիպտը կշարունակվի:",
        "id": "Fitur-fitur yang diperlukan ini akan diinstal terlebih dahulu, kemudian skrip utama akan berlanjut.",
        "is": "Þessir nauðsynlegu eiginleikar verða settir upp fyrst, síðan mun aðalskriftið halda áfram.",
        "it": "Queste funzioni necessarie verranno installate prima, quindi lo script principale continuerà.",
        "ja": "これらの必要な機能がまずインストールされ、その後、メインスクリプトが続行されます。",
        "ka": "ეს საჭირო ფუნქციები ჯერ დაინსტალირდება, შემდეგ მთავარი სკრიპტი გაგრძელდება.",
        "km": "មុខងារដែលចាំបាច់ទាំងនេះនឹងត្រូវបានដំឡើងដំបូង បន្ទាប់មក ស្គ្រីបបន្ថែមនឹងបន្ត។",
        "ko": "이러한 필수 기능이 먼저 설치되고 메인 스크립트가 계속됩니다.",
        "lo": "ຄຸນສົມບັດທີ່ຈໍາເປັນເຫຼົ່ານີ້ຈະຖືກຕິດຕັ້ງກ່ອນ, ຫຼັງຈາກນັ້ນ ສະຄິບທີ່ຕົ້ນຕໍຈະສືບຕໍ່ໄປ.",
        "lt": "Šios reikalingos funkcijos bus sumontuotos pirmiausia, tada tęsis pagrindinė skripta.",
        "lv": "Šīs nepieciešamās funkcijas tiks instalētas vispirms, tad turpināsies galvenais skripts.",
        "mn": "Эдгээр шаардлагатай функцууд эхлээд суулгагдаж, дараа нь үндсэн скрипт үргэлжлүүлнэ.",
        "ms": "Fitur-fitur yang diperlukan ini akan dipasang terlebih dahulu, kemudian skrip utama akan dilanjutkan.",
        "my": "ဤလိုအပ်သည့် အင်္ဂါရပ်များ ကို ဦးစွာ ထည့်သွင်းမည်ဖြစ်ပြီး၊ ထို့နောက် အဓိက စာသားများ သည် ဆက်လက်မည်ဖြစ်သည်။",
        "nb": "Disse nødvendige funksjonene vil bli installert først, deretter vil hovedskriptet fortsette.",
        "ne": "यी आवश्यक सुविधाहरू पहिले स्थापन गरिनेछन्, त्यसपछि मुख्य स्क्रिप्ट जारी रहनेछ।",
        "nl": "Deze vereiste functies worden eerst geïnstalleerd, waarna het hoofdscript wordt voortgezet.",
        "pl": "Te wymagane funkcje będą zainstalowane najpierw, a następnie główny skrypt będzie kontynuować.",
        "pt": "Esses recursos necessários serão instalados primeiro, depois o script principal continuará.",
        "ro": "Aceste funcții necesare vor fi instalate mai întâi, apoi scriptul principal va continua.",
        "ru": "Эти необходимые функции будут установлены в первую очередь, а затем основной скрипт продолжит работу.",
        "sk": "Tieto potrebné funkcie budú nainštalované ako prvé, potom bude pokračovať hlavný skript.",
        "sl": "Te potrebne funkcije bodo najprej nameščene, nato pa se bo glavni skript nadaljeval.",
        "sq": "Këto veçori të nevojshme do të instalohen fillimisht, pastaj skripti kryesor do të vazhdojë.",
        "sr": "Ове потребне функције ће бити инсталиране прво, а затим ће главна скрипта наставити.",
        "sv": "Dessa obligatoriska funktioner kommer att installeras först, sedan fortsätter huvudskriptet.",
        "sw": "Vipengele hivi vya mahitaji vitakamatia kwanza, kisha hati kuu itaendelea.",
        "ta": "இந்த தேவையான அம்சங்கள் முதலில் நிறுவப்படும், பிறகு முக்கிய திரைப்பதிவு தொடரும்.",
        "tg": "Ин хусусиятҳои талаботӣ аввал насб шудаанд, баъди он раёи асосӣ идома хоҳад ёфт.",
        "th": "ฟีเจอร์ที่จำเป็นเหล่านี้จะถูกติดตั้งก่อน จากนั้นสคริปต์หลักจะดำเนินการต่อ",
        "tl": "Ang mga kinakailangang feature na ito ay ilalagay muna, pagkatapos ang pangunahing script ay magpapatuloy.",
        "tr": "Bu gerekli özellikler önce yüklenecek, sonra ana betiği devam edecektir.",
        "uk": "Ці необхідні функції будуть встановлені спочатку, потім основний скрипт продовжиться.",
        "ur": "یہ ضروری خصوصیات پہلے انسٹال کی جائیں گی، پھر اہم اسکرپٹ جاری رہے گی۔",
        "uz": "Bu kerakli xususiyatlar avval o'rnatiladi, so'ng asosiy skript davom etadi.",
        "vi": "Các tính năng cần thiết này sẽ được cài đặt trước, sau đó tập lệnh chính sẽ tiếp tục.",
        "zh": "这些必需的功能将首先安装，然后主脚本将继续进行。",
    },
}

# Skip 'en' since it's already added
for key, lang_translations in translations.items():
    for lang, translation in lang_translations.items():
        file_path = os.path.join(lang_dir, f"{lang}.json")
        if os.path.exists(file_path):
            with open(file_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            data[key] = translation
            with open(file_path, "w", encoding="utf-8") as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            print(f"Added {key} to {lang}.json")
        else:
            print(f"File {file_path} does not exist")
